# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

[[main]]
  name = "Home"
  url = "#about"
  weight = 10
  
[[main]]
  name = "Quickstart Guide"  # A link title for your page.
  url = "quickstart/"  # The URL of your page.
  weight = 49  # The position of your page in the menu.
  
[[main]]
  name = "Downloads"  # A link title for your page.
  url = "downloads/"  # The URL of your page.
  weight = 52  # The position of your page in the menu.
    
[[main]]
  name = "Model Repository"  # A link title for your page.
  url = "repository/"  # The URL of your page.
  weight = 51  # The position of your page in the menu.
  
[[main]]
  name = "Support"
  url = "faq/"
  weight = 61

# Link to a PDF of your resume/CV from the menu.
# To enable, copy your resume/CV to `static/files/cv.pdf` and uncomment the lines below.
# [[main]]
#    name = "CV"
#    url = "files/cv.pdf"
#    weight = 70
